#line 2 "ro.flex.c"

#line 4 "ro.flex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer data_yy_create_buffer
#define yy_delete_buffer data_yy_delete_buffer
#define yy_flex_debug data_yy_flex_debug
#define yy_init_buffer data_yy_init_buffer
#define yy_flush_buffer data_yy_flush_buffer
#define yy_load_buffer_state data_yy_load_buffer_state
#define yy_switch_to_buffer data_yy_switch_to_buffer
#define yyin data_yyin
#define yyleng data_yyleng
#define yylex data_yylex
#define yylineno data_yylineno
#define yyout data_yyout
#define yyrestart data_yyrestart
#define yytext data_yytext
#define yywrap data_yywrap
#define yyalloc data_yyalloc
#define yyrealloc data_yyrealloc
#define yyfree data_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE data_yyrestart(data_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int data_yyleng;

extern FILE *data_yyin, *data_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE data_yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-data_yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < data_yyleng; ++yyl )\
                    if ( data_yytext[yyl] == '\n' )\
                        --data_yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up data_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up data_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via data_yyrestart()), so that the user can continue scanning by
	 * just pointing data_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when data_yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int data_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow data_yywrap()'s to do buffer switches
 * instead of setting up a fresh data_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void data_yyrestart (FILE *input_file  );
void data_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE data_yy_create_buffer (FILE *file,int size  );
void data_yy_delete_buffer (YY_BUFFER_STATE b  );
void data_yy_flush_buffer (YY_BUFFER_STATE b  );
void data_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void data_yypop_buffer_state (void );

static void data_yyensure_buffer_stack (void );
static void data_yy_load_buffer_state (void );
static void data_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER data_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE data_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE data_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE data_yy_scan_bytes (yyconst char *bytes,int len  );

void *data_yyalloc (yy_size_t  );
void *data_yyrealloc (void *,yy_size_t  );
void data_yyfree (void *  );

#define yy_new_buffer data_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        data_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            data_yy_create_buffer(data_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        data_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            data_yy_create_buffer(data_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *data_yyin = (FILE *) 0, *data_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int data_yylineno;

int data_yylineno = 1;

extern char *data_yytext;
#define yytext_ptr data_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up data_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	data_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 25
#define YY_END_OF_BUFFER 26
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[124] =
    {   0,
        1,    1,   26,   24,    1,    1,   24,   21,   19,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       24,    1,    0,   23,    0,    0,   21,   20,   20,   20,
        0,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,    0,    0,    0,   22,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,    0,    0,   20,   20,    4,   20,    5,   20,
       20,   20,   20,   20,    6,   20,   20,   20,   13,    2,
        0,   22,   20,   20,   20,   20,    3,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   15,   14,

       20,   20,   20,   20,    7,   20,    8,    9,   16,   18,
       17,   20,   20,   20,   20,   20,   20,   20,   20,   11,
       10,   12,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    5,    7,    5,    5,    8,    5,
        5,    5,    9,    5,    9,   10,    5,   11,   12,   13,
       12,   12,   12,   12,   12,   12,   12,    5,    5,    5,
       14,    5,    5,    5,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   22,   22,   24,   25,   26,   27,   28,
       22,   29,   30,   31,   32,   33,   22,   34,   35,   22,
        5,    5,    5,    5,   36,    5,   22,   22,   22,   22,

       37,   22,   22,   22,   22,   22,   22,   38,   22,   39,
       22,   40,   22,   41,   22,   42,   22,   22,   22,   22,
       22,   22,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[43] =
    {   0,
        1,    1,    1,    2,    2,    2,    2,    1,    2,    2,
        3,    3,    3,    2,    3,    3,    3,    3,    3,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    5,    4,    4,    4,    4,
        4,    4
    } ;

static yyconst flex_int16_t yy_base[128] =
    {   0,
        0,    0,  303,  304,   41,   44,   43,   41,  304,   23,
       29,   43,   37,  266,   46,   30,   45,   48,   38,   41,
        0,   83,   82,   84,   85,   95,  107,  265,   42,   76,
      264,   35,   86,   95,  102,   59,  105,  101,  117,  118,
      104,  108,  107,  263,  139,    0,  141,  138,  127,  122,
      131,  125,  128,  145,  132,  150,  149,  146,  154,  151,
      148,  157,  171,  183,  155,  152,  262,  169,  261,  173,
      164,  183,  182,  189,  260,  170,  188,  181,  259,  258,
      199,  202,  193,  194,  195,  197,  257,  196,  199,  216,
      202,  211,  207,  218,  210,  212,  214,  220,  256,  255,

      230,  222,  215,  224,  244,  221,  243,  242,  241,  229,
      137,  231,  233,  235,  236,  237,  238,  240,  245,  100,
       74,   58,  304,  280,  283,  286,   77
    } ;

static yyconst flex_int16_t yy_def[128] =
    {   0,
      123,    1,  123,  123,  123,  123,  124,  123,  123,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      126,  123,  124,  124,  123,  123,  123,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  124,  127,  124,  123,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  124,  123,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      123,  123,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,

      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,    0,  123,  123,  123,  123
    } ;

static yyconst flex_int16_t yy_nxt[347] =
    {   0,
        4,    5,    6,    5,    4,    7,    4,    4,    4,    4,
        8,    8,    8,    9,   10,   11,   12,   13,   14,   15,
       14,   14,   14,   14,   14,   14,   16,   17,   18,   19,
       20,   14,   14,   14,   14,   21,   14,   14,   14,   14,
       14,   14,   22,   22,   22,   22,   22,   22,   24,   25,
       26,   27,   27,   27,   29,   32,   30,   33,   31,   34,
       36,   51,   37,   38,   31,   31,   39,   42,   41,   43,
       31,   35,   31,   31,   40,   49,   31,   31,   31,   63,
       31,   31,   55,   31,   22,   22,   22,   24,   25,   24,
       25,   23,   45,   31,   31,   46,   46,   46,   50,   46,

       46,   46,   46,   46,   46,   48,   48,   48,   23,   31,
       23,   31,   23,   23,   52,   23,   26,   27,   27,   27,
       53,   31,   47,   47,   47,   47,   47,   54,   56,   57,
       31,   58,   60,   59,   61,   31,   31,   31,   62,   31,
       31,   65,   31,   31,   24,   25,   24,   25,   48,   48,
       48,   66,   31,   31,   67,   68,   64,   31,   69,   70,
       31,   71,   31,   31,   72,   74,   31,   31,   76,   75,
       77,   79,   31,   78,   64,   80,   24,   25,   73,   84,
       31,   31,   87,   31,   31,   31,   31,   31,   83,   31,
       31,   81,   31,   82,   82,   82,   85,   86,   88,   31,

       89,   90,   93,   92,   31,   31,   94,   91,   31,   82,
       82,   82,   82,   82,   82,   95,   31,   31,   31,   98,
       96,   97,  100,   31,   31,   99,  101,  102,   31,   31,
       31,   31,   31,  103,   31,  104,  109,   31,  105,  106,
      110,  107,   31,  108,  112,   31,   31,   31,  114,   31,
       31,   31,  111,   31,  113,   31,   31,   31,  115,   31,
      116,  117,  118,  119,   31,   31,   31,  120,   31,  121,
       31,   31,   31,   31,  122,   31,   31,   31,   31,   31,
       31,   23,   23,   23,   23,   28,   28,   28,   44,   44,
       31,   31,   31,   31,   31,   31,   31,   31,   31,  123,

       31,   31,  123,    3,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123
    } ;

static yyconst flex_int16_t yy_chk[347] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    5,    6,    6,    6,    7,    7,
        8,    8,    8,    8,   10,   11,   10,   12,   10,   13,
       15,   32,   16,   17,   11,   16,   18,   20,   19,   20,
       32,   13,   13,   19,   18,   29,   20,   29,   12,  127,
       17,   15,   36,   18,   22,   22,   22,   23,   23,   24,
       24,   25,   25,  122,   36,   25,   25,   25,   30,   25,

       25,   25,   25,   25,   25,   26,   26,   26,   25,  121,
       25,   30,   25,   25,   33,   25,   27,   27,   27,   27,
       34,   33,   25,   25,   25,   25,   25,   35,   37,   38,
       34,   39,   41,   40,   42,  120,   38,   35,   43,   41,
       37,   49,   43,   42,   45,   45,   47,   47,   48,   48,
       48,   50,   39,   40,   51,   52,   48,   50,   53,   54,
       52,   55,   49,   53,   56,   57,   51,   55,   59,   58,
       59,   61,  111,   60,   48,   62,   63,   63,   56,   66,
       54,   58,   71,   61,   57,   56,   60,   66,   65,   59,
       65,   64,   62,   64,   64,   64,   68,   70,   72,   71,

       73,   74,   77,   76,   68,   76,   78,   74,   70,   81,
       81,   81,   82,   82,   82,   83,   78,   73,   72,   86,
       84,   85,   89,   77,   74,   88,   90,   91,   83,   84,
       85,   88,   86,   92,   89,   93,   98,   91,   94,   95,
      101,   96,   93,   97,  103,   95,   92,   96,  106,   97,
      103,   90,  102,   94,  104,   98,  106,  102,  112,  104,
      113,  114,  115,  116,  110,  101,  112,  117,  113,  118,
      114,  115,  116,  117,  119,  118,  109,  108,  107,  105,
      119,  124,  124,  124,  124,  125,  125,  125,  126,  126,
      100,   99,   87,   80,   79,   75,   69,   67,   44,   31,

       28,   14,    3,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[26] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int data_yy_flex_debug;
int data_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *data_yytext;
#line 1 "ro.flex"
/*************************************************************/
/*************************************************************/
/*File Description  : Robot Data files interpreter with flex */
/*Author            : Wang Zhen                              */
/*Create Date       : 2014.06.10                             */
/*Last Update       : 2014.07.01                             */
/*************************************************************/
/*************************************************************/
/******************************************/
/******************************************/
/*Section 01  : Definitions...            */
/*Author      : Wang Zhen                 */
/*Create Date : 2014.06.10                */
/*Last Update : 2014.07.01                */
/******************************************/
/******************************************/
/******************************************/
/*Part 0101   : Lexical Parser Options... */
/*Author      : Wang Zhen                 */
/*Create Date : 2014.06.10                */
/*Last Update : 2014.07.01                */
/******************************************/
/* The lexical analyser will never work in interactive mode,
 * i.e., it will only process programs saved to files, and never
 * programs being written inter-actively by the user.
 * This option saves the resulting parser from calling the
 * isatty() function, that seems to be generating some compile
 * errors under some (older?) versions of flex.
 */
/* Have the lexical analyser use a 'char *data_yytext' instead of an
 * array of char 'char data_yytext[??]' to store the lexical token.
 */
/* Have the generated lexical analyser keep track of the
 * line number it is currently analysing.
 * This is used to pass up to the syntax parser
 * the number of the line on which the current
 * token was found. It will enable the syntax parser
 * to generate more informatve error messages...
 */
/***************************************************************/
/*Part 0102   : External Variable and Function declarations... */
/*Author      : Wang Zhen                                      */
/*Create Date : 2014.06.10                                     */
/*Last Update : 2014.07.01                                     */
/***************************************************************/
#line 61 "ro.flex"

/* Define TEST_MAIN to include a main() function.
 * Useful for testing the parser generated by flex.
 */
/*#define TEST_MAIN*/

/* Required for strdup() */
#include <string.h>

/* Required only for the declaration of abstract syntax classes
 * (class symbol_c; class token_c; class list_c;)
 * These will not be used in flex, but the token type union defined
 * in ro.tab.h contains pointers to these classes, so we must include
 * it here.
 */
#include "../data_absyntax/data_absyntax.hh"

/* generated by bison.
 * Contains the definition of the token constants, and the
 * token value type YYSTYPE (in our case, a 'const char *')
 */
#include "ro.y.hh"

/* Variable defined by the bison parser,
 * where the value of the tokens will be stored
 */
extern YYSTYPE data_yylval;

/* The name of the file currently being parsed...
 * This variable is declared and read from the code generated by bison!
 */
extern const char *data_current_filename;

#define YY_NO_UNPUT

/* Variable defined by the bison parser.
 * It must be initialised with the location
 * of the token being parsed.
 * This is only needed if we want to keep
 * track of the locations, in order to give
 * more meaningful error messages!
 */
/*
extern YYLTYPE yylloc;
*/
/* Macro that is executed for every action.
 * We use it to pass the location of the token
 * back to the bison parser...
 */
/*
#define YY_USER_ACTION { 					\
	yylloc.first_line = yylloc.last_line = data_yylineno;	\
	yylloc.first_column = yylloc.last_column = 0;		\
	}
 */
/******************************************/
/*Part 0103   : Prelimenary constructs... */
/*Author      : Wang Zhen                 */
/*Create Date : 2014.06.10                */
/*Last Update : 2014.07.10                */
/******************************************/
/*****************************/
/*  Whitespace and comments... */
/*****************************/
/*****************************************/
/* B.1.1 Letters, digits and identifiers */
/*****************************************/
/*******************/
/* B.1.2 Constants */
/*******************/
/******************************/
/* B.1.2.1   Numeric literals */
/******************************/
/*******************************/
/* B.1.2.2   Character Strings */
/*******************************/
/* WARNING:
 * This definition is only valid in ASCII...
 *
 * Flex includes the function print_char() that defines
 * all printable characters portably (i.e. whatever character
 * encoding is currently being used , ASCII, EBCDIC, etc...)
 * Unfortunately, we cannot generate the definition of
 * common_character_representation portably, since flex
 * does not allow definition of sets by subtracting
 * elements in one set from another set.
 * This means we must build up the defintion of
 * common_character_representation using only set addition,
 * which leaves us with the only choice of defining the
 * characters non-portably...
 */
#line 751 "ro.flex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int data_yylex_destroy (void );

int data_yyget_debug (void );

void data_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE data_yyget_extra (void );

void data_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *data_yyget_in (void );

void data_yyset_in  (FILE * in_str  );

FILE *data_yyget_out (void );

void data_yyset_out  (FILE * out_str  );

int data_yyget_leng (void );

char *data_yyget_text (void );

int data_yyget_lineno (void );

void data_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int data_yywrap (void );
#else
extern int data_yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( data_yytext, data_yyleng, 1, data_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( data_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( data_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, data_yyin))==0 && ferror(data_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(data_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int data_yylex (void);

#define YY_DECL int data_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after data_yytext and data_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 185 "ro.flex"

       /*ATTENTION PLEASE! Comments should not be placed */
       /*at the first of lines!*/
       /*ATTENTION PLEASE! Comments should not be //! */
       /******************************************/
       /******************************************/
       /*Section 02  : Rules...                  */
       /*Author      : Wang Zhen                 */
       /*Create Date : 2014.06.10                */
       /*Last Update : 2014.07.10                */
       /******************************************/
       /******************************************/



       /******************************************/
       /******************************************/
       /******************************************/
       /******************************************/
       /*Part 0201   : First things first        */
       /*Author      : Wang Zhen                 */
       /*Create Date : 2014.06.10                */
       /*Last Update : 2014.07.10                */
       /******************************************/
       /******************************************/
       /******************************************/
       /******************************************/

	/*********************************/
	/* Handle all the state changes! */
	/*********************************/

	/***************************************/
	/* Next is to to remove all whitespace */
	/***************************************/

#line 975 "ro.flex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! data_yyin )
			data_yyin = stdin;

		if ( ! data_yyout )
			data_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			data_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				data_yy_create_buffer(data_yyin,YY_BUF_SIZE );
		}

		data_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of data_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 124 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 123 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < data_yyleng; ++yyl )
				if ( data_yytext[yyl] == '\n' )
					   
    data_yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 221 "ro.flex"
/* Eat any whitespace */
	YY_BREAK
/******************************************/
/******************************************/
/******************************************/
/******************************************/
/*Part 0202   : keywords...               */
/*Author      : Wang Zhen                 */
/*Create Date : 2014.06.10                */
/*Last Update : 2014.07.10                */
/******************************************/
/******************************************/
/******************************************/
/******************************************/
/******************************/
/* B 1.2.1 - Numeric Literals */
/******************************/
case 2:
YY_RULE_SETUP
#line 245 "ro.flex"
return TRUE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 246 "ro.flex"
return FALSE;
	YY_BREAK
/***********************************/
/* B 1.3.1 - Elementary Data Types */
/***********************************/
case 4:
YY_RULE_SETUP
#line 250 "ro.flex"
return BOOL;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 251 "ro.flex"
return DINT;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 252 "ro.flex"
return REAL;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 253 "ro.flex"
return STRING;
	YY_BREAK
/*DWORD             return DWORD;*/
/******************************/
/* B 1.3.2 - Robot Data Types */
/******************************/
/*Position data types */
case 8:
YY_RULE_SETUP
#line 260 "ro.flex"
return AXISPOS;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 261 "ro.flex"
return CARTPOS;
	YY_BREAK
/*AXISPOSEXT        return AXISPOSEXT;*/
/*CARTPOSEXT	  return CARTPOSEXT;*/
case 10:
YY_RULE_SETUP
#line 264 "ro.flex"
return ROBAXISPOS;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 265 "ro.flex"
return AUXAXISPOS;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 266 "ro.flex"
return ROBCARTPOS;
	YY_BREAK
/*Reference system data types*/
/*WORLDREFSYS  	  return WORLDREFSYS;
CARTREFSYS	  return CARTREFSYS;
   /*CARTREFSYSEXT	  return CARTREFSYSEXT;*/
/*CARTREFSYSAXIS    return CARTREFSYSAXIS;*/
/*Tool data types*/ 
case 13:
YY_RULE_SETUP
#line 275 "ro.flex"
return TOOL;
	YY_BREAK
/*TOOLSTATIC	  return TOOLSTATIC;*/
/*Overlapping data types*/ 
case 14:
YY_RULE_SETUP
#line 279 "ro.flex"
return OVLREL;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 280 "ro.flex"
return OVLABS;
	YY_BREAK
/*Dynamic data types*/
case 16:
YY_RULE_SETUP
#line 283 "ro.flex"
return DYNAMIC;
	YY_BREAK
/* World reference system */
/* World  		  return WORLD;*/
/* Percentage */
case 17:
YY_RULE_SETUP
#line 287 "ro.flex"
return PERCENT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 288 "ro.flex"
return PERC200;
	YY_BREAK
/********************************/
/* B 1.3.3 - Derived data types */
/********************************/
case 19:
YY_RULE_SETUP
#line 293 "ro.flex"
return ASSIGN;
	YY_BREAK
/******************************************/
/******************************************/
/******************************************/
/******************************************/
/*Part 0203   : Values...                 */
/*Author      : Wang Zhen                 */
/*Create Date : 2014.06.10                */
/*Last Update : 2014.07.10                */
/******************************************/
/******************************************/
/******************************************/
/******************************************/
/*****************************************/
/* B 1.1 Identifiers                     */
/*****************************************/
case 20:
YY_RULE_SETUP
#line 318 "ro.flex"
{
		   data_yylval.ID=strdup(data_yytext);
		   return identifier_token;
		}
	YY_BREAK
/******************************/
/* B.1.2.1   Numeric literals */
/******************************/
case 21:
YY_RULE_SETUP
#line 326 "ro.flex"
{data_yylval.ID=strdup(data_yytext); return integer_token;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 327 "ro.flex"
{data_yylval.ID=strdup(data_yytext); return real_token;}
	YY_BREAK
/* {binary_integer}	{data_yylval.ID=strdup(data_yytext);      
            return   binary_integer_token;}*/
/* {octal_integer} 	{data_yylval.ID=strdup(data_yytext); 
                return octal_integer_token;}*/
/* {hex_integer} 		{data_yylval.ID=strdup(data_yytext); 
             return hex_integer_token;}*/
/*******************************/
/* B.1.2.2   Character Strings */
/*******************************/
case 23:
YY_RULE_SETUP
#line 338 "ro.flex"
{data_yylval.ID=strdup(data_yytext); return character_string_token;}
	YY_BREAK
/* The end of the file ... */
case YY_STATE_EOF(INITIAL):
#line 341 "ro.flex"
{yyterminate();}
	YY_BREAK
/******************************************/
/******************************************/
/******************************************/
/******************************************/
/*Part 0204   : The leftovers...          */
/*Author      : Wang Zhen                 */
/*Create Date : 2014.06.10                */
/*Last Update : 2014.07.10                */
/******************************************/
/******************************************/
/******************************************/
/******************************************/
/* do the single character tokens...
      *  e.g.:  ':'  '('  ')'  ','  '+' '-' ...
      */
case 24:
YY_RULE_SETUP
#line 369 "ro.flex"
{return data_yytext[0];}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 377 "ro.flex"
ECHO;
	YY_BREAK
#line 1280 "ro.flex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed data_yyin at a new source and called
			 * data_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = data_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( data_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * data_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of data_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					data_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			data_yyrestart(data_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) data_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 124 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 124 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 123);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up data_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --data_yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					data_yyrestart(data_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( data_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve data_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    data_yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void data_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        data_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            data_yy_create_buffer(data_yyin,YY_BUF_SIZE );
	}

	data_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	data_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void data_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		data_yypop_buffer_state();
	 *		data_yypush_buffer_state(new_buffer);
     */
	data_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	data_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (data_yywrap()) processing, but the only time this flag
	 * is looked at is after data_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void data_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	data_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE data_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) data_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in data_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) data_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in data_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	data_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with data_yy_create_buffer()
 * 
 */
    void data_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		data_yyfree((void *) b->yy_ch_buf  );

	data_yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a data_yyrestart() or at EOF.
 */
    static void data_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	data_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then data_yy_init_buffer was _probably_
     * called from data_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void data_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		data_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void data_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	data_yyensure_buffer_stack();

	/* This block is copied from data_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from data_yy_switch_to_buffer. */
	data_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void data_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	data_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		data_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void data_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)data_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in data_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)data_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in data_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE data_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) data_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in data_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	data_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to data_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       data_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE data_yy_scan_string (yyconst char * yystr )
{
    
	return data_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to data_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE data_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) data_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in data_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = data_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in data_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up data_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		data_yytext[data_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = data_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		data_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int data_yyget_lineno  (void)
{
        
    return data_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *data_yyget_in  (void)
{
        return data_yyin;
}

/** Get the output stream.
 * 
 */
FILE *data_yyget_out  (void)
{
        return data_yyout;
}

/** Get the length of the current token.
 * 
 */
int data_yyget_leng  (void)
{
        return data_yyleng;
}

/** Get the current token.
 * 
 */

char *data_yyget_text  (void)
{
        return data_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void data_yyset_lineno (int  line_number )
{
    
    data_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see data_yy_switch_to_buffer
 */
void data_yyset_in (FILE *  in_str )
{
        data_yyin = in_str ;
}

void data_yyset_out (FILE *  out_str )
{
        data_yyout = out_str ;
}

int data_yyget_debug  (void)
{
        return data_yy_flex_debug;
}

void data_yyset_debug (int  bdebug )
{
        data_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from data_yylex_destroy(), so don't allocate here.
     */

    /* We do not touch data_yylineno unless the option is enabled. */
    data_yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    data_yyin = stdin;
    data_yyout = stdout;
#else
    data_yyin = (FILE *) 0;
    data_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * data_yylex_init()
     */
    return 0;
}

/* data_yylex_destroy is for both reentrant and non-reentrant scanners. */
int data_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		data_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		data_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	data_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * data_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *data_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *data_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void data_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see data_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 377 "ro.flex"



/******************************************/
/******************************************/
/*Section 03  : User Code...              */
/*Author      : Wang Zhen                 */
/*Create Date : 2014.06.10                */
/*Last Update : 2014.07.01                */
/******************************************/
/******************************************/

/*************************************************/
/*Part 0301   : Utility function definitions...  */
/*Author      : Wang Zhen                        */
/*Create Date : 2014.06.10                       */
/*Last Update : 2014.07.01                       */
/*************************************************/

/* Called by flex when it reaches the end-of-file */
int data_yywrap(void)
{
  /* We reached the end of the input file... */

  /* Should we continue with another file? */
  /* If so:
   *   open the new file...
   *   return 0;
   */

  /* to we stop processing...
   *
   *   return 1;
   */


  return 1;  /* Stop scanning at end of input file. */
}


