/* A Bison parser, made by GNU Bison 3.0.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2013 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output.  */
#define YYBISON 1

/* Bison version.  */
#define YYBISON_VERSION "3.0.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1


/* Substitute the variable and function names.  */
#define yyparse         pro_yyparse
#define yylex           pro_yylex
#define yyerror         pro_yyerror
#define yydebug         pro_yydebug
#define yynerrs         pro_yynerrs

#define yylval          pro_yylval
#define yychar          pro_yychar
#define yylloc          pro_yylloc

/* Copy the first part of user declarations.  */
#line 19 "rop.y" /* yacc.c:339  */

/*******************************************************/
/*Part 0101   : Macro definitions and declarations of  */
/*              funtions and variables that are used   */
/*              in the actions in the grammar rules... */
/*Author      : Wang Zhen                              */
/*Create Date : 2014.06.20                             */
/*Last Update : 2014.07.07                             */
/*******************************************************/

/* required for strdup()  */
#include <string.h>	

/* declare the token parser generated by flex... */
int pro_yylex(void);

/* declare the error handler defined at the end of this file */
void  pro_yyerror (const char *error_msg);

/* produce a more verbose parsing error message */
#define YYERROR_VERBOSE

/* Include debuging code.
 * Printing of debug info must then be activated by setting
 * the variable yydebug to 1.
 */
#define YYDEBUG 0

/* file with declaration of absyntax classes... */
#include "../program_absyntax/program_absyntax.hh"

/* file with declaration of token constants. Generated by bison! */
#include "rop.y.hh"

/* file with the declarations of symbol tables... */
#include "../program_util/symtable.hh"


/*********************************/
/* The global symbol tables...   */
/*********************************/
/* NOTE: declared static because they are not accessed
 *       directly by the lexical parser (flex), but rather
 *       through the function pro_get_identifier_token()
 */

/* A symbol table to store library elements*/
/* e.g: <function_name,function_decl> (no function_decl)
        <program_name, program_decl> (every program file is a program that can be called by other programs)
 */
static robot_program_file_process::symtable_c<int, BOGUS_TOKEN_ID> library_element_symtable;

/* A symbol table to store the declared variables of the program currently being parsed...
 */
/*static symtable_c<int, BOGUS_TOKEN_ID> variable_element_symtable;*/

/*************************/
/* global variables...   */
/*************************/
static robot_program_file_process::symbol_c *tree_root = NULL;

/* The name of the file currently being parsed...
 * Note that flex accesses and updates this global variable
 */
const char *program_current_filename = NULL;


/************************/
/* forward declarations */
/************************/

/* print an error message */
void pro_print_err_msg(const char *filename, int lineno, const char *additional_error_msg);



#line 152 "rop.y.cc" /* yacc.c:339  */

# ifndef YY_NULLPTR
#  if defined __cplusplus && 201103L <= __cplusplus
#   define YY_NULLPTR nullptr
#  else
#   define YY_NULLPTR 0
#  endif
# endif

/* Enabling verbose error messages.  */
#ifdef YYERROR_VERBOSE
# undef YYERROR_VERBOSE
# define YYERROR_VERBOSE 1
#else
# define YYERROR_VERBOSE 0
#endif

/* In a future release of Bison, this section will be replaced
   by #include "rop.y.hh".  */
#ifndef YY_PRO_YY_ROP_Y_HH_INCLUDED
# define YY_PRO_YY_ROP_Y_HH_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int pro_yydebug;
#endif

/* Token type.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    BOGUS_TOKEN_ID = 258,
    identifier_token = 259,
    integer_token = 260,
    real_token = 261,
    TRUE = 262,
    FALSE = 263,
    character_string_token = 264,
    AND = 265,
    OR = 266,
    NOT = 267,
    LT = 268,
    LE = 269,
    GT = 270,
    GE = 271,
    EQ = 272,
    NE = 273,
    ASSIGN = 274,
    CALL = 275,
    IF = 276,
    THEN = 277,
    ELSE = 278,
    ELSEIF = 279,
    END_IF = 280,
    WHILE = 281,
    DO = 282,
    END_WHILE = 283,
    LOOP = 284,
    END_LOOP = 285,
    standard_function_name_token = 286,
    standard_robot_instruction_token = 287
  };
#endif

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE YYSTYPE;
union YYSTYPE
{
#line 114 "rop.y" /* yacc.c:355  */

    robot_program_file_process::symbol_c *leaf;
    robot_program_file_process::list_c	*list;
    char 	*ID;	/* token value */

#line 231 "rop.y.cc" /* yacc.c:355  */
};
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif

/* Location type.  */
#if ! defined YYLTYPE && ! defined YYLTYPE_IS_DECLARED
typedef struct YYLTYPE YYLTYPE;
struct YYLTYPE
{
  int first_line;
  int first_column;
  int last_line;
  int last_column;
};
# define YYLTYPE_IS_DECLARED 1
# define YYLTYPE_IS_TRIVIAL 1
#endif


extern YYSTYPE pro_yylval;
extern YYLTYPE pro_yylloc;
int pro_yyparse (void);

#endif /* !YY_PRO_YY_ROP_Y_HH_INCLUDED  */

/* Copy the second part of user declarations.  */

#line 260 "rop.y.cc" /* yacc.c:358  */

#ifdef short
# undef short
#endif

#ifdef YYTYPE_UINT8
typedef YYTYPE_UINT8 yytype_uint8;
#else
typedef unsigned char yytype_uint8;
#endif

#ifdef YYTYPE_INT8
typedef YYTYPE_INT8 yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef YYTYPE_UINT16
typedef YYTYPE_UINT16 yytype_uint16;
#else
typedef unsigned short int yytype_uint16;
#endif

#ifdef YYTYPE_INT16
typedef YYTYPE_INT16 yytype_int16;
#else
typedef short int yytype_int16;
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif ! defined YYSIZE_T
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned int
# endif
#endif

#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif

#ifndef YY_ATTRIBUTE
# if (defined __GNUC__                                               \
      && (2 < __GNUC__ || (__GNUC__ == 2 && 96 <= __GNUC_MINOR__)))  \
     || defined __SUNPRO_C && 0x5110 <= __SUNPRO_C
#  define YY_ATTRIBUTE(Spec) __attribute__(Spec)
# else
#  define YY_ATTRIBUTE(Spec) /* empty */
# endif
#endif

#ifndef YY_ATTRIBUTE_PURE
# define YY_ATTRIBUTE_PURE   YY_ATTRIBUTE ((__pure__))
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
#endif

#if !defined _Noreturn \
     && (!defined __STDC_VERSION__ || __STDC_VERSION__ < 201112)
# if defined _MSC_VER && 1200 <= _MSC_VER
#  define _Noreturn __declspec (noreturn)
# else
#  define _Noreturn YY_ATTRIBUTE ((__noreturn__))
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YYUSE(E) ((void) (E))
#else
# define YYUSE(E) /* empty */
#endif

#if defined __GNUC__ && 407 <= __GNUC__ * 100 + __GNUC_MINOR__
/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN \
    _Pragma ("GCC diagnostic push") \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")\
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# define YY_IGNORE_MAYBE_UNINITIALIZED_END \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif


#if ! defined yyoverflow || YYERROR_VERBOSE

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* ! defined yyoverflow || YYERROR_VERBOSE */


#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYLTYPE_IS_TRIVIAL && YYLTYPE_IS_TRIVIAL \
             && defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yytype_int16 yyss_alloc;
  YYSTYPE yyvs_alloc;
  YYLTYPE yyls_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE) + sizeof (YYLTYPE)) \
      + 2 * YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, (Count) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  3
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   187

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  41
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  40
/* YYNRULES -- Number of rules.  */
#define YYNRULES  76
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  124

/* YYTRANSLATE[YYX] -- Symbol number corresponding to YYX as returned
   by yylex, with out-of-bounds checking.  */
#define YYUNDEFTOK  2
#define YYMAXUTOK   287

#define YYTRANSLATE(YYX)                                                \
  ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, without out-of-bounds checking.  */
static const yytype_uint8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,    37,     2,     2,
      38,    39,    35,    33,    40,    34,     2,    36,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    31,    32
};

#if YYDEBUG
  /* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_uint16 yyrline[] =
{
       0,   279,   279,   291,   292,   294,   301,   302,   307,   319,
     320,   321,   324,   329,   330,   331,   335,   357,   363,   365,
     372,   380,   388,   393,   402,   403,   409,   410,   415,   416,
     418,   423,   424,   426,   428,   430,   436,   437,   439,   445,
     446,   448,   450,   455,   459,   462,   467,   468,   470,   503,
     514,   515,   517,   526,   527,   528,   529,   530,   539,   547,
     554,   559,   561,   568,   569,   575,   583,   584,   589,   595,
     603,   610,   612,   617,   618,   622,   623
};
#endif

#if YYDEBUG || YYERROR_VERBOSE || 0
/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "$end", "error", "$undefined", "BOGUS_TOKEN_ID", "identifier_token",
  "integer_token", "real_token", "TRUE", "FALSE", "character_string_token",
  "AND", "OR", "NOT", "LT", "LE", "GT", "GE", "EQ", "NE", "ASSIGN", "CALL",
  "IF", "THEN", "ELSE", "ELSEIF", "END_IF", "WHILE", "DO", "END_WHILE",
  "LOOP", "END_LOOP", "standard_function_name_token",
  "standard_robot_instruction_token", "'+'", "'-'", "'*'", "'/'", "'%'",
  "'('", "')'", "','", "$accept", "start", "constant", "numeric_literal",
  "integer_literal", "signed_integer", "real_literal", "signed_real",
  "real", "integer", "boolean_literal", "character_string", "identifier",
  "function_name", "robot_instruction_name", "expression",
  "and_expression", "comparison", "equ_expression", "add_expression",
  "term", "power_expression", "unary_expression", "primary_expression",
  "function_invocation", "statement_list", "statement",
  "assignment_statement", "subprogram_statement", "selection_statement",
  "if_statement", "elseif_statement_list", "elseif_statement",
  "iteration_statement", "while_statement", "loop_statement",
  "robot_statement", "param_assignment_list", "const_expression", "param", YY_NULLPTR
};
#endif

# ifdef YYPRINT
/* YYTOKNUM[NUM] -- (External) token number corresponding to the
   (internal) symbol number NUM (which must be that of a token).  */
static const yytype_uint16 yytoknum[] =
{
       0,   256,   257,   258,   259,   260,   261,   262,   263,   264,
     265,   266,   267,   268,   269,   270,   271,   272,   273,   274,
     275,   276,   277,   278,   279,   280,   281,   282,   283,   284,
     285,   286,   287,    43,    45,    42,    47,    37,    40,    41,
      44
};
# endif

#define YYPACT_NINF -71

#define yypact_value_is_default(Yystate) \
  (!!((Yystate) == (-71)))

#define YYTABLE_NINF -66

#define yytable_value_is_error(Yytable_value) \
  0

  /* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
     STATE-NUM.  */
static const yytype_int16 yypact[] =
{
     -71,     6,    38,   -71,   -71,   -71,     5,    23,    23,     7,
     -71,    17,    10,   -71,   -71,   -71,   -71,   -71,   -71,   -71,
     -71,   -71,   -71,   -71,   -71,   -71,   -71,   -71,    13,   -71,
       8,     8,    23,   -71,   -71,   -71,   -71,   -71,   -71,   -71,
     -71,   -71,   -71,   -71,    22,    12,    33,    51,   150,    43,
      83,   -71,   -71,   -71,   -71,   -71,    -3,    45,    45,   -71,
     -71,    26,    23,   153,   -71,   -71,   -71,   -71,   -71,    -6,
     153,    23,   -71,    23,    23,    23,    23,    23,    23,    23,
      23,    23,    23,    23,    23,   -71,   -71,    52,    40,   -71,
     -71,    62,    33,    61,    51,   150,   150,    43,    43,    43,
      43,    83,    83,   -71,   -71,   -71,   106,   110,   -71,   153,
     -71,    99,   -71,   -71,   -71,   -71,    23,   -71,   -71,   124,
      15,   -71,   -71,    74
};

  /* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
     Performed when YYTABLE does not specify something else to do.  Zero
     means the default is an error.  */
static const yytype_uint8 yydefact[] =
{
      50,     0,     0,     1,    52,    21,     0,     0,     0,     0,
      23,     0,     0,    51,    54,    55,    56,    60,    57,    66,
      67,    53,    59,    17,    16,    18,    19,    20,     0,    22,
       0,     0,     0,    75,     3,     6,     8,     7,    12,    13,
       9,     5,     4,    76,     0,     0,    24,    26,    28,    31,
      36,    39,    43,    44,    48,    46,     0,     0,     0,    73,
      74,     0,     0,     0,    45,    14,    10,    15,    11,     0,
       0,     0,    50,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,    50,    50,    58,     0,    71,
      47,     0,    25,     0,    27,    29,    30,    32,    34,    33,
      35,    37,    38,    40,    41,    42,     0,     0,    70,     0,
      49,     0,    68,    69,    72,    50,     0,    61,    64,     0,
       0,    62,    50,     0
};

  /* YYPGOTO[NTERM-NUM].  */
static const yytype_int8 yypgoto[] =
{
     -71,   -71,   -71,   -71,    57,   -71,   -71,   -71,    82,    58,
     -71,   -71,    -2,   -71,   -71,    -7,    21,    35,    77,    -5,
      87,    64,   -71,    55,   -71,   -70,   -71,   -71,   -71,   -71,
     -71,   -71,   -71,   -71,   -71,   -71,   -71,    59,   -71,   -60
};

  /* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int8 yydefgoto[] =
{
      -1,     1,    33,    34,    35,    36,    37,    38,    39,    40,
      41,    42,    43,    44,    12,    45,    46,    47,    48,    49,
      50,    51,    52,    53,    54,     2,    13,    14,    15,    16,
      17,   111,   118,    18,    19,    20,    21,    88,    61,    55
};

  /* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
     positive, shift that token.  If negative, reduce the rule whose
     number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_int8 yytable[] =
{
      11,    56,    93,    89,    22,    71,     3,    60,    71,     5,
      89,     5,    23,    23,    24,   106,   107,     5,    23,    24,
      25,    26,    27,    71,    85,    69,    71,     5,    23,    24,
      25,    26,    27,    90,    72,    28,    62,   122,    -2,     4,
      57,    58,     5,    73,    29,   119,    30,    31,    63,   114,
      23,    32,   123,    86,    29,    87,    30,    31,     6,     7,
      70,    32,     4,    71,     8,     5,    59,     9,    74,    75,
      10,    97,    98,    99,   100,     4,    80,    81,     5,   108,
     109,     6,     7,    64,   -63,   -63,   -63,     8,    66,    68,
       9,    11,    92,    10,     6,     7,     0,   -65,   -65,   -65,
       8,   110,   109,     9,    11,    11,    10,     4,    94,   120,
       5,     4,    65,    67,     5,    66,    68,    11,    82,    83,
      84,    11,   115,   116,   117,     4,     6,     7,     5,    91,
       6,     7,     8,     0,   112,     9,     8,     0,    10,     9,
     113,     0,    10,     0,     6,     7,   103,   104,   105,   121,
       8,    95,    96,     9,     0,     0,    10,     5,    23,    24,
      25,    26,    27,    76,    77,    78,    79,   101,   102,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,    30,    31
};

static const yytype_int8 yycheck[] =
{
       2,     8,    72,    63,     6,    11,     0,     9,    11,     4,
      70,     4,     5,     5,     6,    85,    86,     4,     5,     6,
       7,     8,     9,    11,    27,    32,    11,     4,     5,     6,
       7,     8,     9,    39,    22,    12,    19,    22,     0,     1,
      33,    34,     4,    10,    31,   115,    33,    34,    38,   109,
       5,    38,   122,    27,    31,    62,    33,    34,    20,    21,
      38,    38,     1,    11,    26,     4,     9,    29,    17,    18,
      32,    76,    77,    78,    79,     1,    33,    34,     4,    39,
      40,    20,    21,    28,    23,    24,    25,    26,    30,    31,
      29,    93,    71,    32,    20,    21,    -1,    23,    24,    25,
      26,    39,    40,    29,   106,   107,    32,     1,    73,   116,
       4,     1,    30,    31,     4,    57,    58,   119,    35,    36,
      37,   123,    23,    24,    25,     1,    20,    21,     4,    70,
      20,    21,    26,    -1,    28,    29,    26,    -1,    32,    29,
      30,    -1,    32,    -1,    20,    21,    82,    83,    84,    25,
      26,    74,    75,    29,    -1,    -1,    32,     4,     5,     6,
       7,     8,     9,    13,    14,    15,    16,    80,    81,    -1,
      -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    -1,    -1,    -1,    -1,    33,    34
};

  /* YYSTOS[STATE-NUM] -- The (internal number of the) accessing
     symbol of state STATE-NUM.  */
static const yytype_uint8 yystos[] =
{
       0,    42,    66,     0,     1,     4,    20,    21,    26,    29,
      32,    53,    55,    67,    68,    69,    70,    71,    74,    75,
      76,    77,    53,     5,     6,     7,     8,     9,    12,    31,
      33,    34,    38,    43,    44,    45,    46,    47,    48,    49,
      50,    51,    52,    53,    54,    56,    57,    58,    59,    60,
      61,    62,    63,    64,    65,    80,    56,    33,    34,    45,
      53,    79,    19,    38,    64,    49,    50,    49,    50,    56,
      38,    11,    22,    10,    17,    18,    13,    14,    15,    16,
      33,    34,    35,    36,    37,    27,    27,    56,    78,    80,
      39,    78,    57,    66,    58,    59,    59,    60,    60,    60,
      60,    61,    61,    62,    62,    62,    66,    66,    39,    40,
      39,    72,    28,    30,    80,    23,    24,    25,    73,    66,
      56,    25,    22,    66
};

  /* YYR1[YYN] -- Symbol number of symbol that rule YYN derives.  */
static const yytype_uint8 yyr1[] =
{
       0,    41,    42,    43,    43,    43,    44,    44,    45,    46,
      46,    46,    47,    48,    48,    48,    49,    50,    51,    51,
      52,    53,    54,    55,    56,    56,    57,    57,    58,    58,
      58,    59,    59,    59,    59,    59,    60,    60,    60,    61,
      61,    61,    61,    62,    63,    63,    64,    64,    64,    65,
      66,    66,    66,    67,    67,    67,    67,    67,    68,    69,
      70,    71,    71,    72,    72,    73,    74,    74,    75,    76,
      77,    78,    78,    79,    79,    80,    80
};

  /* YYR2[YYN] -- Number of symbols on the right hand side of rule YYN.  */
static const yytype_uint8 yyr2[] =
{
       0,     2,     1,     1,     1,     1,     1,     1,     1,     1,
       2,     2,     1,     1,     2,     2,     1,     1,     1,     1,
       1,     1,     1,     1,     1,     3,     1,     3,     1,     3,
       3,     1,     3,     3,     3,     3,     1,     3,     3,     1,
       3,     3,     3,     1,     1,     2,     1,     3,     1,     4,
       0,     2,     2,     1,     1,     1,     1,     1,     3,     2,
       1,     6,     8,     0,     2,     4,     1,     1,     5,     5,
       4,     1,     3,     1,     1,     1,     1
};


#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)
#define YYEMPTY         (-2)
#define YYEOF           0

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                  \
do                                                              \
  if (yychar == YYEMPTY)                                        \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      YYPOPSTACK (yylen);                                       \
      yystate = *yyssp;                                         \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror (YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (0)

/* Error token number */
#define YYTERROR        1
#define YYERRCODE       256


/* YYLLOC_DEFAULT -- Set CURRENT to span from RHS[1] to RHS[N].
   If N is 0, then set CURRENT to the empty location which ends
   the previous symbol: RHS[0] (always defined).  */

#ifndef YYLLOC_DEFAULT
# define YYLLOC_DEFAULT(Current, Rhs, N)                                \
    do                                                                  \
      if (N)                                                            \
        {                                                               \
          (Current).first_line   = YYRHSLOC (Rhs, 1).first_line;        \
          (Current).first_column = YYRHSLOC (Rhs, 1).first_column;      \
          (Current).last_line    = YYRHSLOC (Rhs, N).last_line;         \
          (Current).last_column  = YYRHSLOC (Rhs, N).last_column;       \
        }                                                               \
      else                                                              \
        {                                                               \
          (Current).first_line   = (Current).last_line   =              \
            YYRHSLOC (Rhs, 0).last_line;                                \
          (Current).first_column = (Current).last_column =              \
            YYRHSLOC (Rhs, 0).last_column;                              \
        }                                                               \
    while (0)
#endif

#define YYRHSLOC(Rhs, K) ((Rhs)[K])


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)


/* YY_LOCATION_PRINT -- Print the location on the stream.
   This macro was not mandated originally: define only if we know
   we won't break user code: when these are the locations we know.  */

#ifndef YY_LOCATION_PRINT
# if defined YYLTYPE_IS_TRIVIAL && YYLTYPE_IS_TRIVIAL

/* Print *YYLOCP on YYO.  Private, do not rely on its existence. */

YY_ATTRIBUTE_UNUSED
static unsigned
yy_location_print_ (FILE *yyo, YYLTYPE const * const yylocp)
{
  unsigned res = 0;
  int end_col = 0 != yylocp->last_column ? yylocp->last_column - 1 : 0;
  if (0 <= yylocp->first_line)
    {
      res += YYFPRINTF (yyo, "%d", yylocp->first_line);
      if (0 <= yylocp->first_column)
        res += YYFPRINTF (yyo, ".%d", yylocp->first_column);
    }
  if (0 <= yylocp->last_line)
    {
      if (yylocp->first_line < yylocp->last_line)
        {
          res += YYFPRINTF (yyo, "-%d", yylocp->last_line);
          if (0 <= end_col)
            res += YYFPRINTF (yyo, ".%d", end_col);
        }
      else if (0 <= end_col && yylocp->first_column < end_col)
        res += YYFPRINTF (yyo, "-%d", end_col);
    }
  return res;
 }

#  define YY_LOCATION_PRINT(File, Loc)          \
  yy_location_print_ (File, &(Loc))

# else
#  define YY_LOCATION_PRINT(File, Loc) ((void) 0)
# endif
#endif


# define YY_SYMBOL_PRINT(Title, Type, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Type, Value, Location); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*----------------------------------------.
| Print this symbol's value on YYOUTPUT.  |
`----------------------------------------*/

static void
yy_symbol_value_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep, YYLTYPE const * const yylocationp)
{
  FILE *yyo = yyoutput;
  YYUSE (yyo);
  YYUSE (yylocationp);
  if (!yyvaluep)
    return;
# ifdef YYPRINT
  if (yytype < YYNTOKENS)
    YYPRINT (yyoutput, yytoknum[yytype], *yyvaluep);
# endif
  YYUSE (yytype);
}


/*--------------------------------.
| Print this symbol on YYOUTPUT.  |
`--------------------------------*/

static void
yy_symbol_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep, YYLTYPE const * const yylocationp)
{
  YYFPRINTF (yyoutput, "%s %s (",
             yytype < YYNTOKENS ? "token" : "nterm", yytname[yytype]);

  YY_LOCATION_PRINT (yyoutput, *yylocationp);
  YYFPRINTF (yyoutput, ": ");
  yy_symbol_value_print (yyoutput, yytype, yyvaluep, yylocationp);
  YYFPRINTF (yyoutput, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yytype_int16 *yybottom, yytype_int16 *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yytype_int16 *yyssp, YYSTYPE *yyvsp, YYLTYPE *yylsp, int yyrule)
{
  unsigned long int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %lu):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       yystos[yyssp[yyi + 1 - yynrhs]],
                       &(yyvsp[(yyi + 1) - (yynrhs)])
                       , &(yylsp[(yyi + 1) - (yynrhs)])                       );
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, yylsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args)
# define YY_SYMBOL_PRINT(Title, Type, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif


#if YYERROR_VERBOSE

# ifndef yystrlen
#  if defined __GLIBC__ && defined _STRING_H
#   define yystrlen strlen
#  else
/* Return the length of YYSTR.  */
static YYSIZE_T
yystrlen (const char *yystr)
{
  YYSIZE_T yylen;
  for (yylen = 0; yystr[yylen]; yylen++)
    continue;
  return yylen;
}
#  endif
# endif

# ifndef yystpcpy
#  if defined __GLIBC__ && defined _STRING_H && defined _GNU_SOURCE
#   define yystpcpy stpcpy
#  else
/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
   YYDEST.  */
static char *
yystpcpy (char *yydest, const char *yysrc)
{
  char *yyd = yydest;
  const char *yys = yysrc;

  while ((*yyd++ = *yys++) != '\0')
    continue;

  return yyd - 1;
}
#  endif
# endif

# ifndef yytnamerr
/* Copy to YYRES the contents of YYSTR after stripping away unnecessary
   quotes and backslashes, so that it's suitable for yyerror.  The
   heuristic is that double-quoting is unnecessary unless the string
   contains an apostrophe, a comma, or backslash (other than
   backslash-backslash).  YYSTR is taken from yytname.  If YYRES is
   null, do not copy; instead, return the length of what the result
   would have been.  */
static YYSIZE_T
yytnamerr (char *yyres, const char *yystr)
{
  if (*yystr == '"')
    {
      YYSIZE_T yyn = 0;
      char const *yyp = yystr;

      for (;;)
        switch (*++yyp)
          {
          case '\'':
          case ',':
            goto do_not_strip_quotes;

          case '\\':
            if (*++yyp != '\\')
              goto do_not_strip_quotes;
            /* Fall through.  */
          default:
            if (yyres)
              yyres[yyn] = *yyp;
            yyn++;
            break;

          case '"':
            if (yyres)
              yyres[yyn] = '\0';
            return yyn;
          }
    do_not_strip_quotes: ;
    }

  if (! yyres)
    return yystrlen (yystr);

  return yystpcpy (yyres, yystr) - yyres;
}
# endif

/* Copy into *YYMSG, which is of size *YYMSG_ALLOC, an error message
   about the unexpected token YYTOKEN for the state stack whose top is
   YYSSP.

   Return 0 if *YYMSG was successfully written.  Return 1 if *YYMSG is
   not large enough to hold the message.  In that case, also set
   *YYMSG_ALLOC to the required number of bytes.  Return 2 if the
   required number of bytes is too large to store.  */
static int
yysyntax_error (YYSIZE_T *yymsg_alloc, char **yymsg,
                yytype_int16 *yyssp, int yytoken)
{
  YYSIZE_T yysize0 = yytnamerr (YY_NULLPTR, yytname[yytoken]);
  YYSIZE_T yysize = yysize0;
  enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
  /* Internationalized format string. */
  const char *yyformat = YY_NULLPTR;
  /* Arguments of yyformat. */
  char const *yyarg[YYERROR_VERBOSE_ARGS_MAXIMUM];
  /* Number of reported tokens (one for the "unexpected", one per
     "expected"). */
  int yycount = 0;

  /* There are many possibilities here to consider:
     - If this state is a consistent state with a default action, then
       the only way this function was invoked is if the default action
       is an error action.  In that case, don't check for expected
       tokens because there are none.
     - The only way there can be no lookahead present (in yychar) is if
       this state is a consistent state with a default action.  Thus,
       detecting the absence of a lookahead is sufficient to determine
       that there is no unexpected or expected token to report.  In that
       case, just report a simple "syntax error".
     - Don't assume there isn't a lookahead just because this state is a
       consistent state with a default action.  There might have been a
       previous inconsistent state, consistent state with a non-default
       action, or user semantic action that manipulated yychar.
     - Of course, the expected token list depends on states to have
       correct lookahead information, and it depends on the parser not
       to perform extra reductions after fetching a lookahead from the
       scanner and before detecting a syntax error.  Thus, state merging
       (from LALR or IELR) and default reductions corrupt the expected
       token list.  However, the list is correct for canonical LR with
       one exception: it will still contain any token that will not be
       accepted due to an error action in a later state.
  */
  if (yytoken != YYEMPTY)
    {
      int yyn = yypact[*yyssp];
      yyarg[yycount++] = yytname[yytoken];
      if (!yypact_value_is_default (yyn))
        {
          /* Start YYX at -YYN if negative to avoid negative indexes in
             YYCHECK.  In other words, skip the first -YYN actions for
             this state because they are default actions.  */
          int yyxbegin = yyn < 0 ? -yyn : 0;
          /* Stay within bounds of both yycheck and yytname.  */
          int yychecklim = YYLAST - yyn + 1;
          int yyxend = yychecklim < YYNTOKENS ? yychecklim : YYNTOKENS;
          int yyx;

          for (yyx = yyxbegin; yyx < yyxend; ++yyx)
            if (yycheck[yyx + yyn] == yyx && yyx != YYTERROR
                && !yytable_value_is_error (yytable[yyx + yyn]))
              {
                if (yycount == YYERROR_VERBOSE_ARGS_MAXIMUM)
                  {
                    yycount = 1;
                    yysize = yysize0;
                    break;
                  }
                yyarg[yycount++] = yytname[yyx];
                {
                  YYSIZE_T yysize1 = yysize + yytnamerr (YY_NULLPTR, yytname[yyx]);
                  if (! (yysize <= yysize1
                         && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
                    return 2;
                  yysize = yysize1;
                }
              }
        }
    }

  switch (yycount)
    {
# define YYCASE_(N, S)                      \
      case N:                               \
        yyformat = S;                       \
      break
      YYCASE_(0, YY_("syntax error"));
      YYCASE_(1, YY_("syntax error, unexpected %s"));
      YYCASE_(2, YY_("syntax error, unexpected %s, expecting %s"));
      YYCASE_(3, YY_("syntax error, unexpected %s, expecting %s or %s"));
      YYCASE_(4, YY_("syntax error, unexpected %s, expecting %s or %s or %s"));
      YYCASE_(5, YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s"));
# undef YYCASE_
    }

  {
    YYSIZE_T yysize1 = yysize + yystrlen (yyformat);
    if (! (yysize <= yysize1 && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
      return 2;
    yysize = yysize1;
  }

  if (*yymsg_alloc < yysize)
    {
      *yymsg_alloc = 2 * yysize;
      if (! (yysize <= *yymsg_alloc
             && *yymsg_alloc <= YYSTACK_ALLOC_MAXIMUM))
        *yymsg_alloc = YYSTACK_ALLOC_MAXIMUM;
      return 1;
    }

  /* Avoid sprintf, as that infringes on the user's name space.
     Don't have undefined behavior even if the translation
     produced a string with the wrong number of "%s"s.  */
  {
    char *yyp = *yymsg;
    int yyi = 0;
    while ((*yyp = *yyformat) != '\0')
      if (*yyp == '%' && yyformat[1] == 's' && yyi < yycount)
        {
          yyp += yytnamerr (yyp, yyarg[yyi++]);
          yyformat += 2;
        }
      else
        {
          yyp++;
          yyformat++;
        }
  }
  return 0;
}
#endif /* YYERROR_VERBOSE */

/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg, int yytype, YYSTYPE *yyvaluep, YYLTYPE *yylocationp)
{
  YYUSE (yyvaluep);
  YYUSE (yylocationp);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YYUSE (yytype);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}




/* The lookahead symbol.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Location data for the lookahead symbol.  */
YYLTYPE yylloc
# if defined YYLTYPE_IS_TRIVIAL && YYLTYPE_IS_TRIVIAL
  = { 1, 1, 1, 1 }
# endif
;
/* Number of syntax errors so far.  */
int yynerrs;


/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    int yystate;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus;

    /* The stacks and their tools:
       'yyss': related to states.
       'yyvs': related to semantic values.
       'yyls': related to locations.

       Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* The state stack.  */
    yytype_int16 yyssa[YYINITDEPTH];
    yytype_int16 *yyss;
    yytype_int16 *yyssp;

    /* The semantic value stack.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs;
    YYSTYPE *yyvsp;

    /* The location stack.  */
    YYLTYPE yylsa[YYINITDEPTH];
    YYLTYPE *yyls;
    YYLTYPE *yylsp;

    /* The locations where the error started and ended.  */
    YYLTYPE yyerror_range[3];

    YYSIZE_T yystacksize;

  int yyn;
  int yyresult;
  /* Lookahead token as an internal (translated) token number.  */
  int yytoken = 0;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;
  YYLTYPE yyloc;

#if YYERROR_VERBOSE
  /* Buffer for error messages, and its allocated size.  */
  char yymsgbuf[128];
  char *yymsg = yymsgbuf;
  YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
#endif

#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N), yylsp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  yyssp = yyss = yyssa;
  yyvsp = yyvs = yyvsa;
  yylsp = yyls = yylsa;
  yystacksize = YYINITDEPTH;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yystate = 0;
  yyerrstatus = 0;
  yynerrs = 0;
  yychar = YYEMPTY; /* Cause a token to be read.  */
  yylsp[0] = yylloc;
  goto yysetstate;

/*------------------------------------------------------------.
| yynewstate -- Push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
 yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;

 yysetstate:
  *yyssp = yystate;

  if (yyss + yystacksize - 1 <= yyssp)
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYSIZE_T yysize = yyssp - yyss + 1;

#ifdef yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        YYSTYPE *yyvs1 = yyvs;
        yytype_int16 *yyss1 = yyss;
        YYLTYPE *yyls1 = yyls;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * sizeof (*yyssp),
                    &yyvs1, yysize * sizeof (*yyvsp),
                    &yyls1, yysize * sizeof (*yylsp),
                    &yystacksize);

        yyls = yyls1;
        yyss = yyss1;
        yyvs = yyvs1;
      }
#else /* no yyoverflow */
# ifndef YYSTACK_RELOCATE
      goto yyexhaustedlab;
# else
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        goto yyexhaustedlab;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yytype_int16 *yyss1 = yyss;
        union yyalloc *yyptr =
          (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
        if (! yyptr)
          goto yyexhaustedlab;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
        YYSTACK_RELOCATE (yyls_alloc, yyls);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif
#endif /* no yyoverflow */

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;
      yylsp = yyls + yysize - 1;

      YYDPRINTF ((stderr, "Stack size increased to %lu\n",
                  (unsigned long int) yystacksize));

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }

  YYDPRINTF ((stderr, "Entering state %d\n", yystate));

  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;

/*-----------.
| yybackup.  |
`-----------*/
yybackup:

  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token: "));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = yytoken = YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);

  /* Discard the shifted token.  */
  yychar = YYEMPTY;

  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END
  *++yylsp = yylloc;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- Do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];

  /* Default location.  */
  YYLLOC_DEFAULT (yyloc, (yylsp - yylen), yylen);
  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
        case 2:
#line 279 "rop.y" /* yacc.c:1646  */
    { 
	                  tree_root = new robot_program_file_process::library_c((yyvsp[0].list));
                          (yyval.leaf) = tree_root;}
#line 1543 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 8:
#line 308 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::integer_literal_c(new robot_program_file_process::dint_type_name_c(), (yyvsp[0].leaf));}
#line 1549 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 10:
#line 320 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = (yyvsp[0].leaf);}
#line 1555 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 11:
#line 321 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::neg_int_expression_c((yyvsp[0].leaf));}
#line 1561 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 12:
#line 325 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::real_literal_c(new robot_program_file_process::real_type_name_c(), (yyvsp[0].leaf));}
#line 1567 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 14:
#line 330 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = (yyvsp[0].leaf);}
#line 1573 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 15:
#line 331 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::neg_real_expression_c((yyvsp[0].leaf));}
#line 1579 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 16:
#line 335 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::real_c((yyvsp[0].ID));}
#line 1585 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 17:
#line 357 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::integer_c((yyvsp[0].ID));}
#line 1591 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 18:
#line 363 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::boolean_literal_c(new robot_program_file_process::bool_type_name_c(),
  				    new robot_program_file_process::boolean_true_c());}
#line 1598 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 19:
#line 365 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::boolean_literal_c(new robot_program_file_process::bool_type_name_c(),
				    new robot_program_file_process::boolean_false_c());}
#line 1605 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 20:
#line 373 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::character_string_c((yyvsp[0].ID));}
#line 1611 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 21:
#line 380 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::identifier_c((yyvsp[0].ID));}
#line 1617 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 22:
#line 389 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::identifier_c((yyvsp[0].ID));}
#line 1623 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 23:
#line 394 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::identifier_c((yyvsp[0].ID));}
#line 1629 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 25:
#line 404 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::or_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1635 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 27:
#line 411 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::and_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1641 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 29:
#line 417 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::equ_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1647 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 30:
#line 419 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::notequ_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1653 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 32:
#line 425 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::lt_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1659 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 33:
#line 427 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::gt_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1665 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 34:
#line 429 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::le_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1671 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 35:
#line 431 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::ge_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1677 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 37:
#line 438 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::add_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1683 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 38:
#line 440 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::sub_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1689 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 40:
#line 447 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::mul_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1695 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 41:
#line 449 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::div_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1701 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 42:
#line 451 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::mod_expression_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1707 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 45:
#line 463 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::not_expression_c((yyvsp[0].leaf));}
#line 1713 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 47:
#line 469 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = (yyvsp[-1].leaf);}
#line 1719 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 49:
#line 504 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::function_invocation_c((yyvsp[-3].leaf), (yyvsp[-1].list));}
#line 1725 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 50:
#line 514 "rop.y" /* yacc.c:1646  */
    {(yyval.list) = new robot_program_file_process::statement_list_c();}
#line 1731 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 51:
#line 516 "rop.y" /* yacc.c:1646  */
    {(yyval.list) = (yyvsp[-1].list); (yyval.list)->add_element((yyvsp[0].leaf));}
#line 1737 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 52:
#line 518 "rop.y" /* yacc.c:1646  */
    {(yyval.list) = (yyvsp[-1].list);
	 pro_print_err_msg(program_current_filename, (yylsp[0]).last_line, "error in statement.");
	 /* yychar */
	 yyerrok;
	}
#line 1747 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 58:
#line 540 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::assignment_statement_c((yyvsp[-2].leaf), (yyvsp[0].leaf));}
#line 1753 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 59:
#line 547 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::subprogram_invocation_c((yyvsp[0].leaf));}
#line 1759 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 61:
#line 560 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::if_statement_c((yyvsp[-4].leaf), (yyvsp[-2].list), (yyvsp[-1].list), NULL);}
#line 1765 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 62:
#line 562 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::if_statement_c((yyvsp[-6].leaf), (yyvsp[-4].list), (yyvsp[-3].list), (yyvsp[-1].list));}
#line 1771 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 63:
#line 568 "rop.y" /* yacc.c:1646  */
    {(yyval.list) = new robot_program_file_process::elseif_statement_list_c();}
#line 1777 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 64:
#line 570 "rop.y" /* yacc.c:1646  */
    {(yyval.list) = (yyvsp[-1].list); (yyval.list)->add_element((yyvsp[0].leaf));}
#line 1783 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 65:
#line 576 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::elseif_statement_c((yyvsp[-2].leaf), (yyvsp[0].list));}
#line 1789 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 68:
#line 590 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::while_statement_c((yyvsp[-3].leaf), (yyvsp[-1].list));}
#line 1795 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 69:
#line 596 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::loop_statement_c((yyvsp[-3].leaf), (yyvsp[-1].list));}
#line 1801 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 70:
#line 603 "rop.y" /* yacc.c:1646  */
    {(yyval.leaf) = new robot_program_file_process::robot_instruction_invocation_c((yyvsp[-3].leaf), (yyvsp[-1].list));}
#line 1807 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 71:
#line 611 "rop.y" /* yacc.c:1646  */
    {(yyval.list) = new robot_program_file_process::param_assignment_list_c(); (yyval.list)->add_element((yyvsp[0].leaf));}
#line 1813 "rop.y.cc" /* yacc.c:1646  */
    break;

  case 72:
#line 613 "rop.y" /* yacc.c:1646  */
    {(yyval.list) = (yyvsp[-2].list); (yyval.list)->add_element((yyvsp[0].leaf));}
#line 1819 "rop.y.cc" /* yacc.c:1646  */
    break;


#line 1823 "rop.y.cc" /* yacc.c:1646  */
      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);

  *++yyvsp = yyval;
  *++yylsp = yyloc;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
  if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTOKENS];

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYEMPTY : YYTRANSLATE (yychar);

  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
#if ! YYERROR_VERBOSE
      yyerror (YY_("syntax error"));
#else
# define YYSYNTAX_ERROR yysyntax_error (&yymsg_alloc, &yymsg, \
                                        yyssp, yytoken)
      {
        char const *yymsgp = YY_("syntax error");
        int yysyntax_error_status;
        yysyntax_error_status = YYSYNTAX_ERROR;
        if (yysyntax_error_status == 0)
          yymsgp = yymsg;
        else if (yysyntax_error_status == 1)
          {
            if (yymsg != yymsgbuf)
              YYSTACK_FREE (yymsg);
            yymsg = (char *) YYSTACK_ALLOC (yymsg_alloc);
            if (!yymsg)
              {
                yymsg = yymsgbuf;
                yymsg_alloc = sizeof yymsgbuf;
                yysyntax_error_status = 2;
              }
            else
              {
                yysyntax_error_status = YYSYNTAX_ERROR;
                yymsgp = yymsg;
              }
          }
        yyerror (yymsgp);
        if (yysyntax_error_status == 2)
          goto yyexhaustedlab;
      }
# undef YYSYNTAX_ERROR
#endif
    }

  yyerror_range[1] = yylloc;

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval, &yylloc);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:

  /* Pacify compilers like GCC when the user code never invokes
     YYERROR and the label yyerrorlab therefore never appears in user
     code.  */
  if (/*CONSTCOND*/ 0)
     goto yyerrorlab;

  yyerror_range[1] = yylsp[1-yylen];
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYTERROR;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;

      yyerror_range[1] = *yylsp;
      yydestruct ("Error: popping",
                  yystos[yystate], yyvsp, yylsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  yyerror_range[2] = yylloc;
  /* Using YYLLOC is tempting, but would change the location of
     the lookahead.  YYLOC is available though.  */
  YYLLOC_DEFAULT (yyloc, yyerror_range, 2);
  *++yylsp = yyloc;

  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturn;

/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturn;

#if !defined yyoverflow || YYERROR_VERBOSE
/*-------------------------------------------------.
| yyexhaustedlab -- memory exhaustion comes here.  |
`-------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  /* Fall through.  */
#endif

yyreturn:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval, &yylloc);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  yystos[*yyssp], yyvsp, yylsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif
#if YYERROR_VERBOSE
  if (yymsg != yymsgbuf)
    YYSTACK_FREE (yymsg);
#endif
  return yyresult;
}
#line 628 "rop.y" /* yacc.c:1906  */

/******************************************/
/******************************************/
/*Section 03  : User code...              */
/*Author      : Wang Zhen                 */
/*Create Date : 2014.06.20                */
/*Last Update : 2014.07.07                */
/******************************************/
/******************************************/
#include <stdio.h>	/* required for printf() */
#include <errno.h>
#include "../program_util/symtable.hh"

/* variables defined in code generated by flex... */
extern FILE *pro_yyin;
extern int pro_yylineno;
extern char *pro_yytext;

/* The following function is called automatically by bison whenever it comes across
 * an error. Unfortunately it calls this function before executing the code that handles
 * the error itself, so we cannot print out the correct line numbers of the error location
 * over here.
 * Our solution is to store the current error message in a global variable, and have all
 * error action handlers call the function pro_print_err_msg() after setting the location
 * (line number) variable correctly.
 */

const char *pro_current_error_msg;

void pro_yyerror (const char *error_msg) {
  //fprintf(stderr, "In file '%s': error %d: %s happen at line %d with the content is '%s'\n", program_current_filename, pro_yynerrs , error_msg, pro_yylineno, pro_yytext); 
   pro_current_error_msg = error_msg;
}

void pro_print_err_msg(const char *filename, int lineno, const char *additional_error_msg) {
  fprintf(stderr, "error %d: %s\n", yynerrs, additional_error_msg);
  fprintf(stderr, "%s:%d: %s\n", filename, lineno, pro_current_error_msg);
}

int pro_get_identifier_token(const char *identifier_str) {
//  std::cout << "pro_get_identifier_token(" << identifier_str << "): \n";
  int token_id;

    if ((token_id = library_element_symtable.find_value(identifier_str)) == library_element_symtable.end_value())
      return identifier_token;
  return token_id;
}

/*
 * Join two strings together. Allocate space with malloc(3).
 */
static char *strdup2(const char *a, const char *b) {
  char *res = (char *)malloc(strlen(a) + strlen(b) + 1);

  if (!res)
    return NULL;
  return strcat(strcpy(res, a), b);  /* safe, actually */
}

/*
const char *standard_structure_type_names[] = {
//Position data types
"AXISPOS","CARTPOS","AXISPOSEXT","CARTPOSEXT","ROBAXISPOS","AUXAXISPOS","ROBCARTPOS",
//Reference system data types
"WORLDREFSYS","CARTREFSYS","CARTREFSYSEXT","CARTREFSYSAXIS",
//Tool data types
"TOOL","TOOLSTATIC",
//Overlapping data types
"OVLREL","OVLABS",
//Dynamic data types
"DYNAMIC",
//Percentage
"PERCENT","PERC200",

NULL

};*/

const char *standard_function_names[] = {
// 2.5.1.5.2  Numerical functions
//   Table 23 - Standard functions of one numeric variable
"ABS","SQRT","EXP","SIN","COS","TAN","ASIN","ACOS","ATAN",
// 2.5.1.5.3  Bit string functions
//   Table 25 - Standard bit shift functions
//"SHL","SHR","ROR","ROL",

/* end of array marker! Do not remove! */
NULL

/* Note (a):
 *  This function has a name equal to a reserved keyword.
 *  This means that adding it here is irrelevant because the
 *  lexical parser will consider it the XXX token before
 *  it interprets it as an identifier and looks it up
 *  in the library elements symbol table.
 */
};

const char *standard_robot_instructions[] = {
//Robot instructions
//   Robot movements
"PTP","Lin","Circ",
//   Settings
"Dyn","DynOvr","Ovl","Ramp","RefSys","Tool","OriMode",
//   System functions
"WaitTime","Stop","Info","Warning","Error",
/* end of array marker! Do not remove! */
NULL

/* Note (a):
 *  This function has a name equal to a reserved keyword.
 *  This means that adding it here is irrelevant because the
 *  lexical parser will consider it the XXX token before
 *  it interprets it as an identifier and looks it up
 *  in the library elements symbol table.
 */
};

int program_stage1_2(const char *filename, robot_program_file_process::symbol_c **tree_root_ref) {
 /* if by any chance the library is not complete, we
   * now add the missing reserved keywords to the list!!!
   */

//Adding standard functions
  for(int i = 0; standard_function_names[i] != NULL; i++)
    if (library_element_symtable.find_value(standard_function_names[i]) ==
        library_element_symtable.end_value())
      library_element_symtable.insert(standard_function_names[i], standard_function_name_token);

//Adding standard robot instructions
  for(int i = 0; standard_robot_instructions[i] != NULL; i++)
    if (library_element_symtable.find_value(standard_robot_instructions[i]) ==
        library_element_symtable.end_value())
      library_element_symtable.insert(standard_robot_instructions[i], standard_robot_instruction_token);

#if YYDEBUG
  pro_yydebug = 1;
#endif
  
//Handle recursive robot_directory
  FILE *in_file = NULL;

  if((in_file = fopen(filename, "r")) == NULL) {
    char *errmsg = strdup2("Error opening main file ", filename);
    perror(errmsg);
    free(errmsg);
    return -1;
  }

  /* now parse the input file... */
  pro_yyin = in_file;
  pro_yylineno = 1;
  program_current_filename = filename;
  if (pro_yyparse() != 0)
  {
    printf("pro_yyparse occurs error!\n");
    exit(EXIT_FAILURE);
  }

  if (pro_yynerrs > 0) {
    fprintf (stderr, "\nFound %d error(s). Bailing out!\n", pro_yynerrs /* global variable */);
    exit(EXIT_FAILURE);
  }

  if (tree_root_ref != NULL)
    *tree_root_ref = tree_root;

  //library_element_symtable.print();
  library_element_symtable.reset();

  fclose(in_file);
  return 0;
}

